### ISSUE TITLE
Provide Dockerfile(s) for frontend and backend

### ISSUE THREAD

**Issue by maximekuhn** [Meliodas-1O/modernMoodle#23]
In order to facilitate deployment, we should create a Dockerfile for the backend and a Dockerfile for the frontend.
We also need to provide a docker-compose file.

The goal is to be able to deploy with a single command:
```shell
docker compose up -d --build
```

**Comment by maximekuhn** [comment]
Note that the backend should not be publicly available

**Comment by maximekuhn** [comment]
Mb the backend (expressJS API) must be publicly avaiable. Otherwise the react frontend will have no way to make requests. However, if we are other services (for instance video encoding), we should make them private. The express.js API will be able to interact with them if required.

**Comment by Meliodas-1O** [comment]
That seems logic to me !
Let's do that
