### ISSUE TITLE
Fix nginx for frontend dynamic URLs

### ISSUE THREAD

**Issue by maximekuhn** [Meliodas-1O/modernMoodle#38]
Fix nginx so /topic/:id and other routes do not return 404

**Comment by maximekuhn** [comment]
After further investigations, it seems that `react-router` perform client side routing and thus, when navigating to `/admin` or `/topic/:id`, there is no request made to the server.

This means that we don't really need to change the nginx default configuration file.

However, I'll still do it to add host access logs and to always redirect to `build/index.html`.

**Comment by maximekuhn** [comment]
PR made, see #39

**Comment by Meliodas-1O** [comment]
Sorry for my late reply
Great.

**Comment by maximekuhn** [comment]
merged to dev, see https://github.com/Meliodas-1O/modernMoodle/pull/39
