### ISSUE TITLE
Change filenames to increase code readability

### ISSUE THREAD

**Issue by maximekuhn** [Meliodas-1O/modernMoodle#7]
Currently, we have typescript files with models, interfaces and actual implementation.
  
For instance, we have :  
- `topic_dao.ts`, the interface
- `postgres_topics_dao.ts`, the actual implementation
  
I think we could change `topic_dao.ts` to `topic_dao.interface.ts` and `postgres_topic_dao.ts` to `postgres_topic_dao.impl.ts`.  
We could do the same for interfaces in every directories.

**Comment by maximekuhn** [comment]
What do you think @Meliodas-1O ?

**Comment by Meliodas-1O** [comment]
Good idea !
Let's do it ! @maximekuhn
